services:

  db:
    image: postgres
    restart: always
    container_name: gmail-project
    environment:
      POSTGRES_USER: mywhatsapp1234
      POSTGRES_PASSWORD: mywhatsapp1234
      POSTGRES_DB: mywhatsapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./TheScemaTables.sql:/docker-entrypoint-initdb.d/TheScemaTables.sql


volumes:
  db_data:


